import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',  
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%'
  },
  imagemLogo: {
    width: 200,  
    height: 200,
    borderRadius: 90,  
    alignSelf: 'center',
    bottom: 120
  },
  title: {
    fontSize: 36, 
    fontWeight: '700',
    color: '#1E90FF',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',  
    textShadowOffset: { width: 1, height: 3 },
    textShadowRadius: 8,
    fontFamily: 'Poppins-SemiBold',
    letterSpacing: 0.8,
    textAlign: 'center',
    margin: 30,
    bottom:140
  },
  input: {
    width: '100%',  
    height: 50,  
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 18,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: '#dfe6e9',
    fontSize: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    bottom: 80
  
  },
  button: {
    width: '100%',
    backgroundColor: '#0984e3',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#0985e3ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
    bottom: 60
  },
  registro:{
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 1,
    marginRight: 60,
    bottom: 30
  }, 
  modal: {
    backgroundColor: '#fff',
    width: '80%',
    marginTop: 200,
    marginBottom: 200,
    marginLeft: '10%',
    marginRight: '10%',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#dfe6e9',
    borderWidth: 2,
    borderRadius: 20,
  },
  titleText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#1E90FF',
    textShadowColor: '#aaa',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    fontFamily: 'Poppins-Italic',
    fontStyle: 'italic',
    textAlign: 'center',
    top: 40,
    left: 0,
    right: 0,
  },
  button2: {
    backgroundColor: '#28a745',  
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginVertical: 15,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#28a745',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  textInput: {
    width: '80%',
    height: 45,
    borderColor: '#ddd',  
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    marginVertical: 10,
    backgroundColor: '#f9f9f9',
    fontSize: 16,
    color: '#333',
  },
  fecharButton: {
    backgroundColor: '#FF4D4D',
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 20,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#FF4D4D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  fecharButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  text: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  button4: {
    backgroundColor: '#fff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 12,
    marginVertical: 10,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    bottom: 0,
    left: 0,
    right: 0,
  },
  viewInput: {
    width: '80%',
    height: '60%'
  }
});
